## **1. Import libraries**

In [5]:
import pandas as pd
import numpy as np
import re

## **2. Load dataset**

In [6]:
jobs = pd.read_csv("job_descriptions.csv")

In [7]:
users = pd.read_csv("resume_dataset.csv")

**Display data**

In [ ]:
jobs.head()

,Job Id,Experience,Qualifications,Salary Range,location,Country,latitude,longitude,Work Type,Company Size,...,Contact,Job Title,Role,Job Portal,Job Description,Benefits,skills,Responsibilities,Company,Company Profile
0,1089843540111562,5 to 15 Years,M.Tech,$59K-$99K,Douglas,Isle of Man,54.2361,-4.5481,Intern,26801,...,001-381-930-7517x737,Digital Marketing Specialist,Social Media Manager,Snagajob,Social Media Managers oversee an organizations...,"{'Flexible Spending Accounts (FSAs), Relocatio...","Social media platforms (e.g., Facebook, Twitte...","Manage and grow social media accounts, create ...",Icahn Enterprises,"{""Sector"":""Diversified"",""Industry"":""Diversifie..."
1,398454096642776,2 to 12 Years,BCA,$56K-$116K,Ashgabat,Turkmenistan,38.9697,59.5563,Intern,100340,...,461-509-4216,Web Developer,Frontend Web Developer,Idealist,Frontend Web Developers design and implement u...,"{'Health Insurance, Retirement Plans, Paid Tim...","HTML, CSS, JavaScript Frontend frameworks (e.g...","Design and code user interfaces for websites, ...",PNC Financial Services Group,"{""Sector"":""Financial Services"",""Industry"":""Com..."
2,481640072963533,0 to 12 Years,PhD,$61K-$104K,Macao,"Macao SAR, China",22.1987,113.5439,Temporary,84525,...,9687619505,Operations Manager,Quality Control Manager,Jobs2Careers,Quality Control Managers establish and enforce...,"{'Legal Assistance, Bonuses and Incentive Prog...",Quality control processes and methodologies St...,Establish and enforce quality control standard...,United Services Automobile Assn.,"{""Sector"":""Insurance"",""Industry"":""Insurance: P..."
3,688192671473044,4 to 11 Years,PhD,$65K-$91K,Porto-Novo,Benin,9.3077,2.3158,Full-Time,129896,...,+1-820-643-5431x47576,Network Engineer,Wireless Network Engineer,FlexJobs,"Wireless Network Engineers design, implement, ...","{'Transportation Benefits, Professional Develo...",Wireless network design and architecture Wi-Fi...,"Design, configure, and optimize wireless netwo...",Hess,"{""Sector"":""Energy"",""Industry"":""Mining, Crude-O..."
4,117057806156508,1 to 12 Years,MBA,$64K-$87K,Santiago,Chile,-35.6751,-71.5429,Intern,53944,...,343.975.4702x9340,Event Manager,Conference Manager,Jobs2Careers,A Conference Manager coordinates and manages c...,"{'Flexible Spending Accounts (FSAs), Relocatio...",Event planning Conference logistics Budget man...,Specialize in conference and convention planni...,Cairn Energy,"{""Sector"":""Energy"",""Industry"":""Energy - Oil & ..."

In [ ]:
jobs.tail()

,Job Id,Experience,Qualifications,Salary Range,location,Country,latitude,longitude,Work Type,Company Size,...,Contact,Job Title,Role,Job Portal,Job Description,Benefits,skills,Responsibilities,Company,Company Profile
281806,536559139369868,1 to 14 Years,MCA,$59K-$116K,Yaren District (de facto),Nauru,-0.5228,166.9315,Full-Time,109544,...,580.281.0865,Front-End Engineer,UI/UX Front-End Developer,Snagajob,UI/UX Front-End Developers focus on creating u...,"{'Employee Referral Programs, Financial Counse...",UI/UX design Frontend web development Wirefram...,Focus on user interface (UI) and user experien...,Cipla,"{""Sector"":""Pharmaceuticals"",""Industry"":""Pharma..."
281807,2305290747010431,4 to 9 Years,BBA,$60K-$114K,Tallinn,Estonia,58.5953,25.0136,Part-Time,53300,...,001-917-329-4308x7186,Software Engineer,Backend Developer,Dice,A Backend Developer is tasked with building an...,"{'Tuition Reimbursement, Stock Options or Equi...",Proficiency in one or more backend programming...,Develop server-side logic and databases using ...,Graphic Packaging Holding,"{""Sector"":""Packaging"",""Industry"":""Packaging, C..."
281808,1004919580096557,2 to 9 Years,PhD,$55K-$114K,Jakarta,Indonesia,-0.7893,113.9213,Intern,88696,...,+1-256-959-0452x4134,Sales Manager,Key Account Manager,Internships.com,"Manage key client accounts, build strong relat...","{'Flexible Spending Accounts (FSAs), Relocatio...",Key account management Relationship building S...,Build and maintain relationships with key clie...,Public Service Enterprise Group,"{""Sector"":""Utilities"",""Industry"":""Utilities: G..."
281809,3097576671257291,2 to 10 Years,B.Com,$58K-$91K,Pristina,Kosovo,42.6026,20.9030,Part-Time,35287,...,(295)666-7109,Landscape Designer,Sustainable Landscape Specialist,Snagajob,Sustainable Landscape Specialists focus on cre...,"{'Tuition Reimbursement, Stock Options or Equi...",Sustainable landscape design Native plant sele...,Focus on environmentally friendly and sustaina...,AmerisourceBergen,"{""Sector"":""Healthcare"",""Industry"":""Wholesalers..."
281810,2013840472033665,2 to 9 Years,BBA,$61K-$118K,Port Vila,Vanuatu,-15.3767,166.9592,Intern,46832,...,001-966-594-7037x877,Research Scientist,Senior Re,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
users.head()

,Name,YearsExperience,Skills,Education,JobRole
0,Fatima Noor,1,"Leadership, Deep Learning, Communication, Proj...",Masters,Project Manager
1,Hassan Raza,4,"Project Management, Java, Leadership, Python",Bachelors,Data Analyst
2,Sara Ahmed,10,"Deep Learning, Data Analysis, Project Manageme...",Bachelors,Data Analyst
3,Sara Ahmed,6,"Excel, Python, Project Management, Leadership,...",PhD,Project Manager
4,Hassan Raza,10,"Data Analysis, Project Management, Deep Learni...",PhD,Data Scientist

In [ ]:
users.tail()

,Name,YearsExperience,Skills,Education,JobRole
295,Hassan Raza,10,"Excel, Python, SQL, Data Analysis, Deep Learning",Bachelors,Project Manager
296,Hassan Raza,4,"SQL, Data Analysis, Communication, Project Man...",Masters,Data Scientist
297,David Lee,7,"Machine Learning, Deep Learning, Data Analysis...",Bachelors,Data Scientist
298,Ali Khan,10,"Excel, Machine Learning, Java, Data Analysis, ...",Bachelors,ML Engineer
299,John Smith,10,"Project Management, Java, Deep Learning",Masters,Data Scientist

**Dataset information**

In [ ]:
jobs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 281811 entries, 0 to 281810
Data columns (total 23 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Job Id            281811 non-null  int64
 1   Experience        281811 non-null  object
 2   Qualifications    281811 non-null  object
 3   Salary Range      281811 non-null  object
 4   location          281811 non-null  object
 5   Country           281811 non-null  object
 6   latitude          281811 non-null  float64
 7   longitude         281811 non-null  float64
 8   Work Type         281811 non-null  object
 9   Company Size      281811 non-null  int64
 10  Job Posting Date  281811 non-null  object
 11  Preference        281811 non-null  object
 12  Contact Person    281811 non-null  object
 13  Contact           281811 non-null  object
 14  Job Title         281811 non-null  object
 15  Role              281811 non-null  object
 16  Job Portal        281810 non-null  object
 17  Job Description   281810 non-null  object
 18  Benefits          281810 non-null  object
 19  skills            281810 non-null  object
 20  Responsibilities  281810 non-null  object
 21  Company           281810 non-null  object
 22  Company Profile   280893 non-null  object
dtypes: float64(2), int64(2), object(19)
memory usage: 49.5+ MB

In [ ]:
users.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             300 non-null    object
 1   YearsExperience  300 non-null    int64
 2   Skills           300 non-null    object
 3   Education        300 non-null    object
 4   JobRole          300 non-null    object
dtypes: int64(1), object(4)
memory usage: 11.8+ KB

In [8]:
print(jobs.iloc[:10])

             Job Id     Experience Qualifications Salary Range      location  \
0  1089843540111562  5 to 15 Years         M.Tech    $59K-$99K       Douglas
1   398454096642776  2 to 12 Years            BCA   $56K-$116K      Ashgabat
2   481640072963533  0 to 12 Years            PhD   $61K-$104K         Macao
3   688192671473044  4 to 11 Years            PhD    $65K-$91K    Porto-Novo
4   117057806156508  1 to 12 Years            MBA    $64K-$87K      Santiago
5   116831420231957  4 to 12 Years            MCA    $59K-$93K      Brussels
6  1292168246729889  3 to 15 Years            PhD   $63K-$103K   George Town
7  1498778686197107   2 to 8 Years          M.Com   $65K-$102K    SÃ£o TomÃ©
8  1680293940995740   2 to 9 Years            BBA   $65K-$102K          Male
9   255627812588102  1 to 10 Years            BBA    $60K-$80K  Saint John's

                 Country  latitude  longitude  Work Type  Company Size  ...  \
0            Isle of Man   54.2361    -4.5481     Intern       26801.0  ...
1           Turkmenistan   38.9697    59.5563     Intern      100340.0  ...
2       Macao SAR, China   22.1987   113.5439  Temporary       84525.0  ...
3                  Benin    9.3077     2.3158  Full-Time      129896.0  ...
4                  Chile  -35.6751   -71.5429     Intern       53944.0  ...
5                Belgium   50.5039     4.4699  Full-Time       23196.0  ...
6         Cayman Islands   19.3133   -81.2546  Temporary       26119.0  ...
7  Sao Tome and Principe    0.1864     6.6131   Contract       40558.0  ...
8               Maldives    3.2028    73.2207  Temporary      105343.0  ...
9    Antigua and Barbuda   17.0608   -61.7964  Full-Time      102069.0  ...

                 Contact                     Job Title  \
0   001-381-930-7517x737  Digital Marketing Specialist
1           461-509-4216                 Web Developer
2             9687619505            Operations Manager
3  +1-820-643-5431x47576              Network Engineer
4      343.975.4702x9340                 Event Manager
5    (973)791-5355x52199               Software Tester
6   001-268-510-4362x789                       Teacher
7     667.202.6824x15893                UX/UI Designer
8    +1-337-946-9956x550                UX/UI Designer
9   001-318-990-0531x978               Wedding Planner

                        Role           Job Portal  \
0       Social Media Manager             Snagajob
1     Frontend Web Developer             Idealist
2    Quality Control Manager         Jobs2Careers
3  Wireless Network Engineer             FlexJobs
4         Conference Manager         Jobs2Careers
5  Quality Assurance Analyst             Snagajob
6          Classroom Teacher             FlexJobs
7    User Interface Designer               Indeed
8       Interaction Designer               Indeed
9         Wedding Consultant  Stack Overflow Jobs

                                     Job Description  \
0  Social Media Managers oversee an organizations...
1  Frontend Web Developers design and implement u...
2  Quality Control Managers establish and enforce...
3  Wireless Network Engineers design, implement, ...
4  A Conference Manager coordinates and manages c...
5  A Quality Assurance Analyst tests software and...
6  A Classroom Teacher educates students in a spe...
7  User Interface Designers focus on the visual a...
8  Interaction Designers specialize in designing ...
9  A Wedding Consultant assists couples in planni...

                                            Benefits  \
0  {'Flexible Spending Accounts (FSAs), Relocatio...
1  {'Health Insurance, Retirement Plans, Paid Tim...
2  {'Legal Assistance, Bonuses and Incentive Prog...
3  {'Transportation Benefits, Professional Develo...
4  {'Flexible Spending Accounts (FSAs), Relocatio...
5  {'Life and Disability Insurance, Stock Options...
6  {'Flexible Spending Accounts (FSAs), Relocatio...
7  {'Employee Assistance Programs (EAP), Tuition ...
8  {'Transportation Benefits, Professional Develo...
9  {'Legal Assistance, Bonuses and Incentive Prog...

                                              skills  \
0  Social media platforms (e.g., Facebook, Twitte...
1  HTML, CSS, JavaScript Frontend frameworks (e.g...
2  Quality control processes and methodologies St...
3  Wireless network design and architecture Wi-Fi...
4  Event planning Conference logistics Budget man...
5  Quality assurance processes Testing methodolog...
6  Teaching pedagogy Classroom management Curricu...
7  UI design principles and best practices Graphi...
8  Interaction design principles User behavior an...
9  Wedding planning Vendor coordination Event man...

                                    Responsibilities  \
0  Manage and grow social media accounts, create ...
1  Design and code user interfaces for websites, ...
2  Establish and enforce quality control standard...
3  Design, configure, and optimize wireless netwo...
4  Specialize in conference and convention planni...
5  Test software applications and systems to iden...
6  Plan and deliver engaging lessons, adapting te...
7  Create visually appealing user interfaces (UI)...
8  Work on interaction design, defining how users...
9  Offer expert advice and guidance to couples pl...

                                 Company  \
0                      Icahn Enterprises
1           PNC Financial Services Group
2       United Services Automobile Assn.
3                                   Hess
4                           Cairn Energy
5  Adani Ports and Special Economic Zone
6                                  FedEx
7                           Ryder System
8          Zee Entertainment Enterprises
9                                    CSX

                                     Company Profile
0  {"Sector":"Diversified","Industry":"Diversifie...
1  {"Sector":"Financial Services","Industry":"Com...
2  {"Sector":"Insurance","Industry":"Insurance: P...
3  {"Sector":"Energy","Industry":"Mining, Crude-O...
4  {"Sector":"Energy","Industry":"Energy - Oil & ...
5  {"Sector":"Infrastructure","Industry":"Ports a...
6  {"Sector":"Logistics","Industry":"Mail, Packag...
7  {"Sector":"Transportation","Industry":"Transpo...
8  {"Sector":"Media & Entertainment","Industry":"...
9  {"Sector":"Transportation","Industry":"Railroa...

[10 rows x 23 columns]

**Check columns**

In [ ]:
jobs.columns

Index(['Job Id', 'Experience', 'Qualifications', 'Salary Range', 'location',
       'Country', 'latitude', 'longitude', 'Work Type', 'Company Size',
       'Job Posting Date', 'Preference', 'Contact Person', 'Contact',
       'Job Title', 'Role', 'Job Portal', 'Job Description', 'Benefits',
       'skills', 'Responsibilities', 'Company', 'Company Profile'],
      dtype='object')

In [ ]:
users.columns

Index(['Name', 'YearsExperience', 'Skills', 'Education', 'JobRole'], dtype='object')

In [ ]:
jobs.isnull().sum()

Job Id                0
Experience            0
Qualifications        0
Salary Range          0
location              0
Country               0
latitude              0
longitude             0
Work Type             0
Company Size          0
Job Posting Date      0
Preference            0
Contact Person        0
Contact               0
Job Title             0
Role                  0
Job Portal            1
Job Description       1
Benefits              1
skills                1
Responsibilities      1
Company               1
Company Profile     918
dtype: int64

**Check missing values**

In [ ]:
users.isnull().sum()

Name               0
YearsExperience    0
Skills             0
Education          0
JobRole            0
dtype: int64

**Handles missing values**

In [ ]:
jobs.fillna(0, inplace=True)

In [ ]:
jobs["Experience"] = jobs["Experience"].astype(str).apply(lambda x: x.split(' ')[0]).astype(int)

## **3. Text preprocessing**

In [ ]:
pip install nltk

Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk) (4.67.3)

In [ ]:
import nltk
import string
import pandas as pd

**Download requried NLTK data**

In [ ]:
nltk.download('stopwords')
nltk.download('punkt')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

True

**Load stopwords**

In [ ]:
from nltk.corpus import stopwords

stop_words = set(stopwords.words('english'))

**Create text cleaning function**

In [ ]:
def clean_text(text):
    # Ensure text is string
    text = str(text)

    # Convert to lowercase
    text = text.lower()

    # Remove punctuation
    text = text.translate(
        str.maketrans('', '', string.punctuation)
    )

    # Split into words
    words = text.split()

    # Remove stopwords
    words = [
        word for word in words
        if word not in stop_words
    ]

    # Join words back
    text = " ".join(words)

    return text

**Apply cleaning to dataset**

In [ ]:
jobs["clean_description"] = jobs["Job Description"].apply(clean_text)

In [ ]:
print(jobs[["Job Description", "clean_description"]].head())

                                     Job Description  \
0  Social Media Managers oversee an organizations...
1  Frontend Web Developers design and implement u...
2  Quality Control Managers establish and enforce...
3  Wireless Network Engineers design, implement, ...
4  A Conference Manager coordinates and manages c...

                                   clean_description
0  social media managers oversee organizations so...
1  frontend web developers design implement user ...
2  quality control managers establish enforce qua...
3  wireless network engineers design implement ma...
4  conference manager coordinates manages confere...

**Remove numbers**

In [ ]:
import re

def clean_text(text):

    text = text.lower()

    text = re.sub(
        r'\d+',
        '',
        text
    )

    text = text.translate(
        str.maketrans('', '', string.punctuation)
    )

    words = text.split()

    words = [
        word for word in words
        if word not in stop_words
    ]

    return " ".join(words)

## **4. Detect Experience Requirement Using NLP (Regex)**

In [ ]:
import re

**Create Experience Detection Function**

In [9]:
import re
import pandas as pd

def detect_experience(text):

    if pd.isnull(text):
        return 0

    text = str(text).lower()

    # Find all numbers in the text
    numbers = re.findall(r'\d+', text)

    if numbers:
        return int(numbers[0])   # take the first number

    return 0

**Apply function to dataset**

In [11]:
jobs["detected_experience"] = jobs["Experience"].apply(detect_experience)

**Job type column**

In [13]:
jobs["job_type"] = jobs["detected_experience"].apply(
    lambda x: "Fresher" if x <= 1 else "Experienced"
)

In [14]:
print(
    jobs[
        ["Experience",
         "detected_experience",
         "job_type"]
    ].head(10)
)

      Experience  detected_experience     job_type
0  5 to 15 Years                    5  Experienced
1  2 to 12 Years                    2  Experienced
2  0 to 12 Years                    0      Fresher
3  4 to 11 Years                    4  Experienced
4  1 to 12 Years                    1      Fresher
5  4 to 12 Years                    4  Experienced
6  3 to 15 Years                    3  Experienced
7   2 to 8 Years                    2  Experienced
8   2 to 9 Years                    2  Experienced
9  1 to 10 Years                    1      Fresher

## **5. Filter only Fresher jobs**

In [15]:
fresher_jobs = jobs[jobs["job_type"] == "Fresher"]

print("Total Fresher Jobs:", len(fresher_jobs))

Total Fresher Jobs: 7128

In [16]:
fresher_jobs.head(10)

,Job Id,Experience,Qualifications,Salary Range,location,Country,latitude,longitude,Work Type,Company Size,...,Role,Job Portal,Job Description,Benefits,skills,Responsibilities,Company,Company Profile,detected_experience,job_type
2,481640072963533,0 to 12 Years,PhD,$61K-$104K,Macao,"Macao SAR, China",22.1987,113.5439,Temporary,84525.0,...,Quality Control Manager,Jobs2Careers,Quality Control Managers establish and enforce...,"{'Legal Assistance, Bonuses and Incentive Prog...",Quality control processes and methodologies St...,Establish and enforce quality control standard...,United Services Automobile Assn.,"{""Sector"":""Insurance"",""Industry"":""Insurance: P...",0,Fresher
4,117057806156508,1 to 12 Years,MBA,$64K-$87K,Santiago,Chile,-35.6751,-71.5429,Intern,53944.0,...,Conference Manager,Jobs2Careers,A Conference Manager coordinates and manages c...,"{'Flexible Spending Accounts (FSAs), Relocatio...",Event planning Conference logistics Budget man...,Specialize in conference and convention planni...,Cairn Energy,"{""Sector"":""Energy"",""Industry"":""Energy - Oil & ...",1,Fresher
9,255627812588102,1 to 10 Years,BBA,$60K-$80K,Saint John's,Antigua and Barbuda,17.0608,-61.7964,Full-Time,102069.0,...,Wedding Consultant,Stack Overflow Jobs,A Wedding Consultant assists couples in planni...,"{'Legal Assistance, Bonuses and Incentive Prog...",Wedding planning Vendor coordination Event man...,Offer expert advice and guidance to couples pl...,CSX,"{""Sector"":""Transportation"",""Industry"":""Railroa...",1,Fresher
13,290761760113904,1 to 8 Years,B.Com,$56K-$86K,Banjul,Gambia,13.4432,-15.3101,Temporary,127900.0,...,Network Security Analyst,FlexJobs,Protect an organizations computer networks and...,"{'Legal Assistance, Bonuses and Incentive Prog...",Network security protocols Intrusion detection...,"Manage and secure computer networks, including...",EnLink Midstream,"{""Sector"":""Energy"",""Industry"":""Pipelines"",""Cit...",1,Fresher
14,1627539131873813,1 to 9 Years,MCA,$57K-$98K,Damascus,Syrian Arab Republic,34.8021,38.9968,Full-Time,92128.0,...,Sales Account Manager,USAJOBS,A Sales Account Manager is responsible for bui...,"{'Casual Dress Code, Social and Recreational A...",Account management Sales strategy Negotiation ...,Manage sales accounts and ensure revenue growt...,NGL Energy Partners,"{""Sector"":""Energy"",""Industry"":""Pipelines"",""Cit...",1,Fresher
17,76902098772934,0 to 11 Years,BA,$55K-$117K,Papeete,French Polynesia,-17.6797,-149.4068,Full-Time,29318.0,...,Content Creator,Jobs2Careers,"Create engaging and relevant content, such as ...","{'Casual Dress Code, Social and Recreational A...","Content creation (e.g., writing, editing, grap...",Create compelling and shareable content for so...,Mondelez International,"{""Sector"":""Food and Beverage"",""Industry"":""Food...",0,Fresher
20,940776147258900,0 to 15 Years,B.Tech,$62K-$120K,Baku,Azerbaijan,40.1431,47.5769,Full-Time,64351.0,...,Legal Secretary,The Muse,Provide administrative support to legal profes...,"{'Employee Assistance Programs (EAP), Tuition ...",Legal administrative tasks Document management...,Provide administrative support to legal profes...,NGL Energy Partners,"{""Sector"":""Energy"",""Industry"":""Pipelines"",""Cit...",0,Fresher
21,1524311163188117,0 to 10 Years,BCA,$64K-$98K,Funafuti,Tuvalu,-7.1095,177.6493,Intern,118041.0,...,Family Nurse Practitioner,Dice,Family Nurse Practitioners specialize in famil...,"{'Childcare Assistance, Paid Time Off (PTO), R...",Family medicine Health assessment Pediatric ca...,"Focus on family-centered care, providing healt...",EasyJet,"{""Sector"":""Travel and Leisure"",""Industry"":""Air...",0,Fresher
22,2508133000944341,1 to 8 Years,M.Tech,$58K-$116K,Asmara,Eritrea,15.1794,39.7823,Intern,40723.0,...,Account Strategist,USAJOBS,Account Strategists work in advertising or mar...,"{'Health Insurance, Retirement Plans, Paid Tim...",Account management Client relations Marketing ...,Develop account strategies and marketing plans...,Otis Worldwide,"{""Sector"":""Elevators & Escalators"",""Industry"":...",1,Fresher
28,1361459669383850,0 to 12 Years,M.Com,$63K-$86K,Funafuti,Tuvalu,-7.1095,177.6493,Intern,93670.0,...,Security Operations Center (SOC) Analyst,Indeed,SOC Analysts work in security operations cente...,"{'Health Insurance, Retirement Plans, Flexible...",SOC operations Security incident response Thre...,Work in SOC teams to monitor and respond to se...,Deutsche Post DHL Group,"{""Sector"":""Logistics"",""Industry"":""Logistics & ...",0,Fresher

In [17]:
fresher_jobs.to_csv("fresher_jobs_filtered.csv", index=False)

## **6. Match User Skills With Jobs**

In [18]:
fresher_jobs = jobs[jobs["job_type"] == "Fresher"]

print("Total Fresher Jobs:", len(fresher_jobs))

fresher_jobs.head()

Total Fresher Jobs: 7128

,Job Id,Experience,Qualifications,Salary Range,location,Country,latitude,longitude,Work Type,Company Size,...,Role,Job Portal,Job Description,Benefits,skills,Responsibilities,Company,Company Profile,detected_experience,job_type
2,481640072963533,0 to 12 Years,PhD,$61K-$104K,Macao,"Macao SAR, China",22.1987,113.5439,Temporary,84525.0,...,Quality Control Manager,Jobs2Careers,Quality Control Managers establish and enforce...,"{'Legal Assistance, Bonuses and Incentive Prog...",Quality control processes and methodologies St...,Establish and enforce quality control standard...,United Services Automobile Assn.,"{""Sector"":""Insurance"",""Industry"":""Insurance: P...",0,Fresher
4,117057806156508,1 to 12 Years,MBA,$64K-$87K,Santiago,Chile,-35.6751,-71.5429,Intern,53944.0,...,Conference Manager,Jobs2Careers,A Conference Manager coordinates and manages c...,"{'Flexible Spending Accounts (FSAs), Relocatio...",Event planning Conference logistics Budget man...,Specialize in conference and convention planni...,Cairn Energy,"{""Sector"":""Energy"",""Industry"":""Energy - Oil & ...",1,Fresher
9,255627812588102,1 to 10 Years,BBA,$60K-$80K,Saint John's,Antigua and Barbuda,17.0608,-61.7964,Full-Time,102069.0,...,Wedding Consultant,Stack Overflow Jobs,A Wedding Consultant assists couples in planni...,"{'Legal Assistance, Bonuses and Incentive Prog...",Wedding planning Vendor coordination Event man...,Offer expert advice and guidance to couples pl...,CSX,"{""Sector"":""Transportation"",""Industry"":""Railroa...",1,Fresher
13,290761760113904,1 to 8 Years,B.Com,$56K-$86K,Banjul,Gambia,13.4432,-15.3101,Temporary,127900.0,...,Network Security Analyst,FlexJobs,Protect an organizations computer networks and...,"{'Legal Assistance, Bonuses and Incentive Prog...",Network security protocols Intrusion detection...,"Manage and secure computer networks, including...",EnLink Midstream,"{""Sector"":""Energy"",""Industry"":""Pipelines"",""Cit...",1,Fresher
14,1627539131873813,1 to 9 Years,MCA,$57K-$98K,Damascus,Syrian Arab Republic,34.8021,38.9968,Full-Time,92128.0,...,Sales Account Manager,USAJOBS,A Sales Account Manager is responsible for bui...,"{'Casual Dress Code, Social and Recreational A...",Account management Sales strategy Negotiation ...,Manage sales accounts and ensure revenue growt...,NGL Energy Partners,"{""Sector"":""Energy"",""Industry"":""Pipelines"",""Cit...",1,Fresher

**Create a sample user**

In [19]:
user_skills = "python sql machine learning data analysis"

**Convert Skills to Lowercase**

In [20]:
fresher_jobs["skills"] = fresher_jobs["skills"].str.lower()

/tmp/ipykernel_7906/2906443590.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fresher_jobs["skills"] = fresher_jobs["skills"].str.lower()

**Create Skill Matching Function**

In [21]:
def skill_match_score(job_skills, user_skills):

    job_words = set(job_skills.split())
    user_words = set(user_skills.split())

    match = job_words.intersection(user_words)

    return len(match)

**Apply matching**

In [22]:
fresher_jobs["match_score"] = fresher_jobs["skills"].apply(
    lambda x: skill_match_score(x, user_skills)
)

/tmp/ipykernel_7906/303174192.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fresher_jobs["match_score"] = fresher_jobs["skills"].apply(

**Get top matching jobs**

In [23]:
recommended_jobs = fresher_jobs.sort_values(
    by="match_score",
    ascending=False
)

**Show Top 10 Recommended Jobs**

In [24]:
recommended_jobs[
    ["Job Title", "Company", "skills", "match_score"]
].head(10)

,Job Title,Company,skills,match_score
21282,Data Analyst,Baxter International,machine learning algorithms and libraries (e.g...,4
14267,Data Analyst,Titan Company,machine learning algorithms and libraries (e.g...,4
6499,Data Scientist,DXC Technology,machine learning algorithms python programming...,4
13510,Data Scientist,Landstar System,machine learning algorithms python programming...,4
13498,Data Analyst,Dr. Reddy's Laboratories,machine learning algorithms and libraries (e.g...,4
12735,Data Analyst,CDW,machine learning algorithms and libraries (e.g...,4
13461,Data Scientist,Celanese,machine learning algorithms python programming...,4
3846,Data Analyst,MTU Aero Engines AG,machine learning algorithms and libraries (e.g...,4
15163,Data Analyst,Morrison Supermarkets,machine learning algorithms and libraries (e.g...,4
16197,Data Analyst,IQVIA Holdings,machine learning algorithms and libraries (e.g...,4

## **7. Cosine Similarity**

In [25]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [26]:
vectorizer = TfidfVectorizer(stop_words="english")

**Convert Job Skills into Vectors**

In [27]:
job_vectors = vectorizer.fit_transform(
    fresher_jobs["skills"]
)

**Convert User Skills into Vector**

In [28]:
user_vector = vectorizer.transform(
    [user_skills]
)

**Calculate Similarity**

In [29]:
similarity_scores = cosine_similarity(
    user_vector,
    job_vectors
)

**Add Similarity Column**

In [30]:
fresher_jobs["similarity_score"] = similarity_scores.flatten()

/tmp/ipykernel_7906/2265990465.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fresher_jobs["similarity_score"] = similarity_scores.flatten()

**Get Top Recommended Jobs**

In [31]:
top_jobs = fresher_jobs.sort_values(
    by="similarity_score",
    ascending=False
)

**Show top 10 jobs**

In [32]:
top_jobs[
    ["Job Title", "Company", "skills", "similarity_score"]
].head(10)

,Job Title,Company,skills,similarity_score
4451,Data Scientist,Unum Group,machine learning algorithms python programming...,0.56051
13510,Data Scientist,Landstar System,machine learning algorithms python programming...,0.56051
13461,Data Scientist,Celanese,machine learning algorithms python programming...,0.56051
4712,Data Scientist,Campbell Soup,machine learning algorithms python programming...,0.56051
7122,Data Scientist,NextEra Energy,machine learning algorithms python programming...,0.56051
5681,Data Scientist,Blackstone,machine learning algorithms python programming...,0.56051
9391,Data Scientist,Arthur J. Gallagher,machine learning algorithms python programming...,0.56051
9671,Data Scientist,Berkshire Hathaway,machine learning algorithms python programming...,0.56051
18035,Data Scientist,SF Express,machine learning algorithms python programming...,0.56051
18525,Data Scientist,Kohl's,machine learning algorithms python programming...,0.56051

## **8. Filter Only Relevant Roles**

**Define Target variables**

In [33]:
target_roles = [
    "data scientist",
    "data analyst",
    "machine learning",
    "ai engineer",
    "data engineer",
    "business analyst"
]

**Filter Jobs by Roles**

In [34]:
filtered_jobs = top_jobs[
    top_jobs["Job Title"].str.lower().str.contains(
        "|".join(target_roles)
    )
]

**Show Final Recommended Jobs**

In [35]:
filtered_jobs[
    ["Job Title", "Company", "similarity_score"]
].head(10)

            Job Title              Company  similarity_score
4451   Data Scientist           Unum Group           0.56051
13510  Data Scientist      Landstar System           0.56051
13461  Data Scientist             Celanese           0.56051
4712   Data Scientist        Campbell Soup           0.56051
7122   Data Scientist       NextEra Energy           0.56051
5681   Data Scientist           Blackstone           0.56051
9391   Data Scientist  Arthur J. Gallagher           0.56051
9671   Data Scientist   Berkshire Hathaway           0.56051
18035  Data Scientist           SF Express           0.56051
18525  Data Scientist               Kohl's           0.56051

In [36]:
filtered_jobs.to_csv(
    "final_recommended_jobs.csv",
    index=False
)

In [40]:
print(sorted(jobs["location"].dropna().unique()))

['Abu Dhabi', 'Abuja', 'Accra', 'Addis Ababa', 'Algiers', 'Amman', 'Amsterdam', 'Andorra la Vella', 'Ankara', 'Antananarivo', 'Apia', 'Ashgabat', 'Asmara', 'AsunciÃ³n', 'Athens', 'Baku', 'Bamako', 'Bandar Seri Begawan', 'Bangkok', 'Bangui', 'Banjul', 'Basseterre', 'Beijing', 'Beirut', 'Belgrade', 'Belmopan', 'Berlin', 'Bern', 'Bishkek', 'Bissau', 'BogotÃ¡', 'Brasilia', 'Bratislava', 'Brazzaville', 'Bridgetown', 'Brussels', 'Bucharest', 'Budapest', 'Buenos Aires', 'Cairo', 'Canberra', 'Capitol Hill, Saipan', 'Caracas', 'Castries', 'Charlotte Amalie', 'Chisinau', 'City of Baghdad', 'City of Port Louis', 'City of Victoria', 'Cockburn Town', 'Conakry', 'Copenhagen', 'Dakar', 'Damascus', 'Dhaka', 'Dili', 'Djibouti (city)', 'Dodoma', 'Doha', 'Douglas', 'Dublin', 'Dushanbe', 'Freetown', 'Funafuti', 'Gaborone', 'Gaza', 'George Town', 'Georgetown', 'Gibraltar', 'Gitega', 'Guatemala City', 'Hagatna', 'Hanoi', 'Harare', 'Havana', 'Helsinki', 'Honiara', 'Islamabad', 'Jakarta', 'Jerusalem', 'Juba', 'Kabul', 'Kampala', 'Kathmandu', 'Khartoum', 'Kigali', 'Kingston', 'Kingstown', 'Kinshasa', 'Kuala Lumpur', 'Kuwait City', 'Kyiv (also known as Kiev)', 'Libreville', 'Lilongwe', 'Lima', 'Lisbon', 'Ljubljana', 'LomÃ©', 'London', 'Luanda', 'Lusaka', 'Luxembourg', 'Macao', 'Madrid', 'Majuro', 'Malabo (de jure),', 'Male', 'Managua', 'Manama', 'Manila', 'Maputo', 'Marigot', 'Maseru', 'Mbabane', 'Mexico City', 'Minsk', 'Mogadishu', 'Monaco', 'Monrovia', 'Montevideo', 'Moroni', 'Moscow', 'Muscat', "N'Djamena", 'Nairobi', 'Nassau', 'Naypyidaw', 'New Delhi', 'Ngerulmud', 'Niamey', 'Nicosia', 'Nouakchott', 'Noumea', 'Nuku?alofa', 'Nur-Sultan', 'Nuuk', 'Oranjestad', 'Oslo', 'Ottawa', 'Ouagadougou', 'Palikir', 'Panama City', 'Papeete', 'Paramaribo', 'Paris', 'Philipsburg', 'Phnom Penh', 'Podgorica', 'Port Moresby', 'Port Vila', 'Port of Spain', 'Port-au-Prince', 'Porto-Novo', 'Prague', 'Praia', 'Pretoria', 'Pristina', 'Quito', 'Rabat', 'ReykjavÃ\xadk', 'Riga', 'Riyadh', 'Road Town', 'Rome', 'Roseau', "Saint George's", "Saint John's", 'San Jose', 'San Juan', 'San Marino', 'San Salvador', 'Sanaa', 'Santiago', 'Santo Domingo', 'Sarajevo', 'Seoul', 'Singapore', 'Skopje', 'Sofia', 'Sri Jayawardenepura Kotte', 'Stockholm', 'Sucre (de jure)', 'Suva', 'SÃ£o TomÃ©', 'Tallinn', 'Tarawa', 'Tashkent', 'Tbilisi', 'Tegucigalpa', 'Tehran', 'The City of Hamilton', 'Thimphu', 'Tirana', 'Tokyo', 'Torshavn', 'Tripoli', 'Tunis', 'Ulaanbaatar', 'Vaduz', 'Valletta', 'Victoria', 'Vienna', 'Vientiane', 'Vilnius', 'Warsaw', 'Washington, D.C.', 'Wellington', 'Willemstad', 'Windhoek', 'Yamoussoukro', 'Yaounde', 'Yaren District (de facto)', 'Yerevan', 'Zagreb']

In [41]:
indian_locations = [
    "Bangalore",
    "Chennai",
    "Hyderabad",
    "Mumbai",
    "Delhi",
    "Pune",
    "Kolkata",
    "Ahmedabad",
    "Noida",
    "Gurgaon",
    "Coimbatore",
    "Trichy",
    "Madurai",
    "Vellore",
    "Visakhapatnam",
    "Kochi",
    "Thiruvananthapuram",
    "Jaipur",
    "Lucknow",
    "Indore",
    "Bhopal",
    "Nagpur",
    "Surat",
    "Vadodara",
    "Patna",
    "Chandigarh"
]

In [43]:
import random

jobs["location"] = [
    random.choice(indian_locations)
    for _ in range(len(jobs))
]

In [44]:
sorted(jobs["location"].unique())

['Ahmedabad',
 'Bangalore',
 'Bhopal',
 'Chandigarh',
 'Chennai',
 'Coimbatore',
 'Delhi',
 'Gurgaon',
 'Hyderabad',
 'Indore',
 'Jaipur',
 'Kochi',
 'Kolkata',
 'Lucknow',
 'Madurai',
 'Mumbai',
 'Nagpur',
 'Noida',
 'Patna',
 'Pune',
 'Surat',
 'Thiruvananthapuram',
 'Trichy',
 'Vadodara',
 'Vellore',
 'Visakhapatnam']

In [46]:
jobs.to_csv(
    "final_recommended_jobs.csv",
    index=False
)

In [47]:
from google.colab import files
files.download("final_recommended_jobs.csv")